### ISSUE TITLE
Poder configurar si se quiere o no usar log en libredte.log

### ISSUE THREAD

**Issue by estebandelaf** [LibreDTE/libredte-plugin-opencart#3]
En https://github.com/LibreDTE/libredte-plugin-opencart/blob/master/upload/admin/model/extension/libredte/order.php (y potencialmente en otros archivos) se escribe un libredte.log se debe crear una configuración llamada `module_libredte_log` en la extensión.

Esta configuración propuesta ya es usada en el código, pero está forzada a un valor verdadero actualmente en 2 partes en el archivo indicado:

`$libredte_info['module_libredte_log'] = true; // TODO mover esto a configuración del módulo`

Falta crear configuración y quitar las 2 líneas de forzado.

**Comment by pabloestremadoyro** [comment]
Se implementó este cambio. Ya está listo el modo Debug, que se pueda habilitar y deshabilitar desde el menú de configuración del módulo.

**Comment by estebandelaf** [comment]
Genial! Gracias!
